# Generated by Django 4.2.5 on 2023-09-23 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ('-expires_at',),
            },
        ),
    ]
