# Generated by Django 4.2.5 on 2023-09-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiringlink',
            options={'ordering': ('-expires_at',)},
        ),
    ]
